// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDfAZcafFNXuxNuzhHOa5KabRfX86R6Do',
    appId: '1:734753240569:web:580e31e90197f77f63f928',
    messagingSenderId: '734753240569',
    projectId: 'projekmobile-3cf4c',
    authDomain: 'projekmobile-3cf4c.firebaseapp.com',
    storageBucket: 'projekmobile-3cf4c.appspot.com',
    measurementId: 'G-WBEPFGKDPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ihq0Gr7n0aYv7FkVPbNtLEQOXQiDi6Y',
    appId: '1:734753240569:android:742fb0efaf86224e63f928',
    messagingSenderId: '734753240569',
    projectId: 'projekmobile-3cf4c',
    storageBucket: 'projekmobile-3cf4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbKYVS7ko7U6PteFRzMDrT0s2_AkogVmU',
    appId: '1:734753240569:ios:4a42ed37b9cf412963f928',
    messagingSenderId: '734753240569',
    projectId: 'projekmobile-3cf4c',
    storageBucket: 'projekmobile-3cf4c.appspot.com',
    iosBundleId: 'com.example.anvayarencang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbKYVS7ko7U6PteFRzMDrT0s2_AkogVmU',
    appId: '1:734753240569:ios:4a42ed37b9cf412963f928',
    messagingSenderId: '734753240569',
    projectId: 'projekmobile-3cf4c',
    storageBucket: 'projekmobile-3cf4c.appspot.com',
    iosBundleId: 'com.example.anvayarencang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDfAZcafFNXuxNuzhHOa5KabRfX86R6Do',
    appId: '1:734753240569:web:bed5a565649caaf563f928',
    messagingSenderId: '734753240569',
    projectId: 'projekmobile-3cf4c',
    authDomain: 'projekmobile-3cf4c.firebaseapp.com',
    storageBucket: 'projekmobile-3cf4c.appspot.com',
    measurementId: 'G-NF1M2Z5XY9',
  );
}
